[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$pdQ6BwDAuDemdK6VUkqpNQ$LXLX17ecRNvnrt3xJkHkwNGKBo6uzHiC/cbXWHju2X/ztfcbuShvT31gpfqzBSwoQRve1KzUgMEaYNk3kSO/TQ
log_level = info

